spring:
  server:
    port: 5000

  datasource:
    url: 'jdbc:postgresql://springbootdb.cb1ryt93ac04.us-east-2.rds.amazonaws.com:5432/student'
    username: wendell
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true